package:
  name: pvapy
  version: {{ environ.get('PVAPY_VERSION', '0.0') }}

source:
  git_rev: {{ environ.get('PVAPY_VERSION', '0.0') }}
  git_url: https://github.com/epics-base/pvaPy
  #path: ../../..

build:
  number: {{ environ.get('BUILD_NUMBER', '1') }}
  script_env:
    - BUILD_FLAGS
  entry_points:
    - pvapy-ad-sim-server=pvapy.cli.adSimServer:main
    - pvapy-mirror-server=pvapy.cli.mirrorServer:main
    - pvapy-hpc-consumer=pvapy.cli.hpcConsumer:main
    - pvapy-hpc-collector=pvapy.cli.hpcCollector:main

test:
  requires:
    - nose

  source_files:
    - test

requirements:
  build:
    - python
    - sphinx
    - sphinx_rtd_theme
    - numpy=1.22             # python >= 3.8
    #- numpy=1.19            # python < 3.8
    - epics-base={{ environ.get('EPICS_BASE_VERSION', '0.0') }}
    - pvapy-boost={{ environ.get('BOOST_VERSION', '0.0') }}
    - pillow
    - pycryptodome
    - rsa

  run:
    - python
    - numpy>=1.22            # python >= 3.8
    #- numpy>=1.19,<1.21     # python < 3.8
    - epics-base={{ environ.get('EPICS_BASE_VERSION', '0.0') }}
    - pvapy-boost={{ environ.get('BOOST_VERSION', '0.0') }}

about:
  home: https://github.com/epics-base/pvaPy
  license: EPICS Open License
  summary: Python library for EPICS PV Access 



