package:
  name: pvapy-boost
  version: {{ environ.get('BOOST_VERSION', '0.0') }}

source:
  url: https://sourceforge.net/projects/boost/files/boost/{{ environ.get('BOOST_VERSION', '0.0') }}/boost_{{ environ.get('BOOST_DOWNLOAD_VERSION', '0.0') }}.tar.gz

build:
  number: {{ environ.get('BUILD_NUMBER', '1') }}
  script_env:
    - PVAPY_USE_CPP11


requirements:
  build:
    - python
    - numpy=2.1            # python >= 3.13
    #- numpy=2.0            # python >= 3.9
    #- numpy=1.22           # python >= 3.8
    #- numpy=1.19           # python < 3.8

  run:
    - python
    - numpy>=2.1           # python >= 3.13
    #- numpy>=2.0           # python >= 3.9
    #- numpy>=1.22,<2.0     # python >= 3.8
    #- numpy>=1.19,<1.21    # python < 3.8

about:
  home: http://www.boost.org
  license: Boost Software License
  license_file: LICENSE_1_0.txt
  summary: Boost python libraries needed by PvaPy 
