package:
  name: epics-base
  version: {{ environ.get('EPICS_BASE_VERSION', '0.0') }}

source:
  url: https://epics.anl.gov/download/base/base-{{ environ.get('EPICS_BASE_VERSION', '0.0') }}.tar.gz
  #url: file:///mnt/PVAPY/BUILD/linux-x86_64/base-{{ environ.get('EPICS_BASE_VERSION', '0.0') }}.tar.gz


build:
  number: {{ environ.get('BUILD_NUMBER', '1') }}
  script_env:
    - BUILD_FLAGS
    - PVAPY_USE_CPP11

requirements:
  build:
    - perl

  run:
    - perl

about:
  home: https://epics.anl.gov/index.php
  license: EPICS Open License
  license_file: LICENSE
  summary: EPICS Base software 

