package:
  name: epics-base
  version: 7.0.1.1

source:
  url: https://epics.anl.gov/download/base/base-7.0.1.1.tar.gz

build:
  number: 1

requirements:
  build:
    - python
    - perl

  run:
    - perl

about:
  home: https://epics.anl.gov/index.php
  license: EPICS Open License
  license_file: LICENSE
  summary: EPICS Base software 

